language: perl
perl:
  - "5.26.0"
sudo: false
before_install:
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
install:
  - cpanm -nq 'DBD::mysql@4.046'
  - cpanm -n --installdeps .
script:
  - perl Build.PL && ./Build build && PERL5LIB=t/ cover -test -report coveralls
