language: perl
perl:
  - "5.26.0"
sudo: true
addon:
  apt:
    update: true
before_install:
  - sudo apt-get install -y libgd-dev
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
install:
  - pwd -P
  - cpanm -nq 'DBD::mysql@4.046' 'Devel::Cover@1.29' 'UR@0.46'
  - cpanm -nq --installdeps .
before_script:
  - coverage-setup
script:
  - cd t/
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -I. -l -j$(test-jobs) .
  - cover
after_success:
  - coverage-report
  - cover -report coveralls
