#!/usr/bin/env lims-perl

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
};

use strict;
use warnings;

use above 'RefImp';

use RefImp::Test::Factory;
use Test::More tests => 2;

my $pkg = 'RefImp::Project::Command::Update::Status';

my %setup;
subtest "setup" => sub{
    plan tests => 1;

    use_ok($pkg) or die;

    $setup{project} = RefImp::Test::Factory->setup_test_project;
    $setup{project}->status('10X done');

};

subtest 'update' => sub{
    plan tests => 3;

    my $update = $pkg->execute(
        projects => [ $setup{project}, ],
        value => 'submitted',
    );
    ok($update->result, 'execute');

    is($setup{project}->status, 'submitted', 'set project status');
    my $psh = RefImp::Project::StatusHistory->get(
        project => $setup{project},
        project_status => 'submitted',
    );
    ok($psh, 'created project status history');

};

done_testing();
