#!/usr/bin/env lims-perl

BEGIN {
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_DBI_NO_COMMIT} = 1;
};

use strict;
use warnings;

use above 'RefImp';

use Test::More;

my $pkg = 'RefImp::Project::StatusHistory';
use_ok($pkg) or die;

subtest 'basics' => sub{
    plan tests => 6;

    my $project = RefImp::Project->create(name => 'Testy McTesterson');
    ok($project, 'create project');

    my $psh = RefImp::Project::StatusHistory->create(
        project => $project,
        project_status => 'new',
    );
    ok($psh, 'create psh');
    is($psh->project, $project, 'psh project');
    is($psh->project_status, 'new', 'psh stautus');
    is($psh->project_status, $project->status, 'set project stautus');
    ok($psh->status_date, 'psh status_date');

};

done_testing();
