#!/usr/bin/env lims-perl

BEGIN {
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_DBI_NO_COMMIT} = 1;
}

use strict;
use warnings;

use above 'RefImp';

use RefImp::Test::Factory;
use Test::More tests => 1;

subtest 'connect' => sub{
    plan tests => 2;

    my $pkg = 'RefImp::Resources::NcbiFtp';
    use_ok($pkg) or die;

    my $test_ftp = RefImp::Test::Factory->setup_test_ftp;
    my $ftp = $pkg->connect;
    is($ftp, $test_ftp, 'connected to ncbi ftp');

};

done_testing();
