#!/usr/bin/env lims-perl

BEGIN {
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_DBI_NO_COMMIT} = 1;
}

use strict;
use warnings;

use above 'RefImp';

use RefImp::Test;
use RefImp::Test::Factory;
use Sub::Install;
use Test::Exception;
use Test::More tests => 4;

my %setup;
subtest 'setup' => sub{
    plan tests => 1;

    $setup{pkg} = 'RefImp::Project::Command::Presubmit';
    use_ok($setup{pkg}) or die;

    $setup{project} = RefImp::Test::Factory->setup_test_project;
    my $clone = RefImp::Test::Factory->setup_test_clone;
    $setup{test_data_dir} = RefImp::Test->test_data_directory_for_package($setup{pkg});

    $setup{finisher} = RefImp::Test::Factory->setup_test_user;

    RefImp::Project::Finisher->create_for_project_and_user(
        project => $setup{project},
        user => $setup{finisher},
    );

    Sub::Install::reinstall_sub({
            code => sub{ diag $_[0]->as_string },
            into => 'MIME::Lite',
            as => 'send',
        });
};

subtest 'cannot presubmit project with incorrect status' => sub{
    plan tests => 2;

    $setup{project}->status('prefinish_done');
    throws_ok(
        sub{
            $setup{pkg}->execute(
                project => $setup{project},
                checker_unix_logins => [ $setup{finisher}->unix_login ],
            );
        },
        qr/Project /,
        'fails w/ incorrect project status',
    );
    is($setup{project}->status, 'prefinish_done', 'did not presubmit')

};

subtest 'presubmit does not proceed unless responding yes' => sub{
    plan tests => 2;

    open my $stdin, '<', \ "NO\n"
        or die "Cannot open STDIN to read from string: $!";
    local *STDIN = $stdin;

    $setup{project}->status('finish_start');
    throws_ok(
        sub{
            $setup{pkg}->execute(
                project => $setup{project},
                checker_unix_logins => [ $setup{finisher}->unix_login ],
            ); 
        },
        qr/Request to not presubmit/,
        'failed to presubmit when responding no',
    );
    is($setup{project}->status, 'finish_start', 'did not presubmit')

};

subtest 'presubmit' => sub{
    plan tests => 2;

    open my $stdin, '<', \ "Y\n"
        or die "Cannot open STDIN to read from string: $!";
    local *STDIN = $stdin;

    my $cmd = $setup{pkg}->execute(
        project => $setup{project},
        checker_unix_logins => [ $setup{finisher}->unix_login ],
    );
    ok($cmd->result, 'execute');
    is($setup{project}->status, 'presubmitted', 'set project status');

};

done_testing();
