package TestEnv;

use strict;
use warnings;

use File::Basename 'dirname';
use File::Spec;
use Sys::Hostname;

my $current_repo_path;
INIT { # runs after compilation, right before execution
    $current_repo_path = resolve_repo_path( (caller())[1] );
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_DBI_NO_COMMIT} = 1;

    my $lib = File::Spec->join($current_repo_path, 'lib');
    eval "use lib '$lib';";
    die "FATAL: $@" if $@;

    my $use = <<USE;
    use RefImp;
    use RefImp::Test;
    use RefImp::Test::Factory;
USE
    eval $use;
    die "FATAL: $@" if $@;

    RefImp::Config::set('ds_testdb_server', File::Spec->join($current_repo_path, 'db', 'test.db'));

    printf(STDERR "***** TEST ENV on %s *****\n", Sys::Hostname::hostname);
}

sub current_repo_path { $current_repo_path };

sub resolve_repo_path {
    my $file = shift;
    die "No file given to resolve lib path!" if not $file;
    die "File given to resolve lib path does not exist!" if not -e $file;
    my @directory_parts = File::Spec->splitdir( File::Spec->rel2abs( dirname($file) ) );
    pop @directory_parts;
    File::Spec->join(@directory_parts);
}

sub test_data_path { File::Spec->join(resolve_repo_path(@_), 't.d'); }

1;

