#!/usr/bin/env perl

use strict;
use warnings 'FATAL';

use List::Util;
use Test::More tests => 7;

use TestEnv;

subtest 'libs' => sub {
    plan tests => 6;

    for my $namespace (qw/ RefImp Tenx Pacbio /) {
        my $pm = join('.', $namespace, 'pm');

        my $in_inc = List::Util::first { /$pm/ } keys %INC;
        ok($in_inc, "$namespace is in INC");

        my $repo_path = TestEnv::repo_path();
        is($INC{$in_inc}, $repo_path->subdir('lib')->file($pm), "$namespace path is correct");
    }

};

subtest 'ENVs' => sub{
    plan tests => 3;

    ok($ENV{UR_DBI_NO_COMMIT}, 'no commit is on');
    ok($ENV{UR_USE_DUMMY_AUTOGENERATED_IDS}, 'use dummy ids is on');

     my $repo_path = TestEnv::repo_path();
     my $bin_path = $repo_path->subdir('bin');
     like($ENV{PATH}, qr#$bin_path#, 'repo bin in path');

};

subtest 'config' => sub{
    plan tests => 6;

    my $repo_path = TestEnv::repo_path();
    my %expected_configs = (
        analysis_directory => $repo_path->subdir('t', 'data', 'analysis'),
        refimp_ds => 'RefImp::DataSource::TestDb',
        refimp_ds_oltp => 'RefImp::DataSource::TestDb',
        ds_testdb_server => $repo_path->subdir('t', 'data', 'test.db'),
        environment => 'test',
        test_data_path => $repo_path->subdir('t', 'data'),
    );
    for my $config_key ( sort keys %expected_configs ) {
        is(RefImp::Config::get($config_key), $expected_configs{$config_key}, $config_key);
    }

};

subtest 'tempdir' => sub{
    plan tests => 2;

    my $tempdir = TestEnv::temp_dir;
    ok($tempdir, 'got tempdir');
    ok(-d $tempdir, 'tempdir exits');

};

subtest 'lims rest api' => sub{
    plan tests => 1;

    my $lims = TestEnv::LimsRestApi::setup();
    ok($lims, 'setup test lims rest api');

};

subtest "ncbi ftp" => sub{
    plan tests => 2;

    my $ftp = TestEnv::NcbiFtp->setup;
    ok($ftp, 'setup test ncbi ftp');
    is(RefImp::Resources::NcbiFtp->connect, $ftp, 'correctly redefined Net::FTP new');

};

subtest 'ncbi biosample' => sub{
    plan tests => 1;

    my $ua = TestEnv::NcbiBiosample->setup;
    ok($ua, 'ncbi biosample');

};

done_testing();
