#!/usr/bin/env lims-perl

use strict;
use warnings;

use File::Spec;
use Test::Exception;
use Test::More tests => 3;

use TestEnv;

subtest 'resolve_repo_path' => sub{
    plan tests => 2;

    throws_ok(sub{ TestEnv::resolve_repo_path(); }, qr/No file given/, 'fails w/o file');
    throws_ok(sub{ TestEnv::resolve_repo_path('/blah'); }, qr/does not exist/, 'fails with invalid file');

};

subtest 'RefImp' => sub {
    plan tests => 2;

    my ($refimp_in_inc) = grep { /RefImp\.pm/ } keys %INC;
    ok($refimp_in_inc, 'RefImp is in INC');

    my $repo_path = TestEnv::resolve_repo_path(__FILE__);
    is($INC{$refimp_in_inc}, File::Spec->join($repo_path, 'lib', 'RefImp.pm'), 'RefImp path is correct');

};

subtest 'ENVs' => sub{
    plan tests => 3;

    is(RefImp::Config::get('environment'), 'test', 'RefImp environment is test');
    ok($ENV{UR_DBI_NO_COMMIT}, 'no commit is on');
    ok($ENV{UR_USE_DUMMY_AUTOGENERATED_IDS}, 'use dummy ids is on');

};

done_testing();
