#!/usr/bin/env lims-perl

BEGIN{
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_DBI_NO_COMMIT} = 1;
}

use strict;
use warnings;

use above 'RefImp';

use Test::More tests => 2;

my $pkg = 'RefImp::User::WorkFunction';
use_ok($pkg) or die;

subtest "basics" => sub{
    plan tests => 3;

    my $wf = $pkg->create(name => 'finishing', status => 'active');
    ok($wf, 'create user work function');
    ok($wf->name, 'name');
    ok($wf->status, 'status');

};

done_testing();
